version: '3.7'
services:
  app:
    build:
      args:
        user: blog
        uid: 1000
      context: ./
      dockerfile: ./.docker/app/Dockerfile
    image: blog_test
    container_name: blog-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - './:/var/www'
    depends_on:
      - db
    networks:
      - bloglist
  db:
    image: 'mysql:5.7'
    container_name: blog-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - './.docker/db:/var/lib/mysql'
    ports:
      - '8101:3306'
    networks:
      - bloglist
  nginx:
    image: 'nginx:alpine'
    container_name: blog-nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - './:/var/www/'
      - './.docker/nginx/conf.d/:/etc/nginx/conf.d/'
    networks:
      - bloglist
networks:
  bloglist:
    driver: bridge
